spring.config.import=optional:file:.env[.properties]

spring.application.name=accommodation-service

server.port=${PORT:8010}

spring.mvc.servlet.path=/api

eureka.instance.lease-renewal-interval-in-seconds=15

eureka.client.service-url.defaultZone=http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:auth_service}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PSWD:12345}
